-- Veritabanında paket var mı kontrol et
SELECT COUNT(*) AS PAKET_SAYISI FROM AKTBLPTSMAS
GO

-- İlk 10 paketi göster
SELECT TOP 10 
  TRANSFER_ID,
  DOCUMENT_NUMBER,
  DOCUMENT_DATE,
  SOURCE_GLN,
  DESTINATION_GLN,
  CREATED_DATE
FROM AKTBLPTSMAS
ORDER BY CREATED_DATE DESC
GO



