-- PTS Paket Transfer Tabloları
-- AKTBLPTSMAS: Master tablo (Paket başlık bilgileri)
-- AKTBLPTSTRA: Transaction tablo (Ürün detayları)

-- Eğer tablolar varsa sil (geliştirme için)
-- IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'AKTBLPTSTRA') AND type in (N'U'))
-- DROP TABLE AKTBLPTSTRA
-- GO

-- IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'AKTBLPTSMAS') AND type in (N'U'))
-- DROP TABLE AKTBLPTSMAS
-- GO

-- Master Tablo: Paket Başlık Bilgileri
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'AKTBLPTSMAS') AND type in (N'U'))
BEGIN
    CREATE TABLE AKTBLPTSMAS (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        TRANSFER_ID BIGINT NOT NULL,
        DOCUMENT_NUMBER NVARCHAR(50) NULL,
        DOCUMENT_DATE DATE NULL,
        SOURCE_GLN NVARCHAR(50) NULL,
        DESTINATION_GLN NVARCHAR(50) NULL,
        ACTION_TYPE NVARCHAR(10) NULL,
        SHIP_TO NVARCHAR(50) NULL,
        NOTE NVARCHAR(500) NULL,
        VERSION NVARCHAR(10) NULL,
        XML_CONTENT NVARCHAR(MAX) NULL,
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        UPDATED_DATE DATETIME NULL
    )
    
    -- Index'ler
    CREATE UNIQUE INDEX IX_AKTBLPTSMAS_TRANSFER_ID ON AKTBLPTSMAS(TRANSFER_ID)
    CREATE INDEX IX_AKTBLPTSMAS_DOCUMENT_DATE ON AKTBLPTSMAS(DOCUMENT_DATE)
    CREATE INDEX IX_AKTBLPTSMAS_SOURCE_GLN ON AKTBLPTSMAS(SOURCE_GLN)
    CREATE INDEX IX_AKTBLPTSMAS_DESTINATION_GLN ON AKTBLPTSMAS(DESTINATION_GLN)
    
    PRINT 'AKTBLPTSMAS tablosu oluşturuldu'
END
ELSE
BEGIN
    PRINT 'AKTBLPTSMAS tablosu zaten mevcut'
END
GO

-- Transaction Tablo: Ürün Detayları (Hiyerarşik Carrier Yapısı ile)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'AKTBLPTSTRA') AND type in (N'U'))
BEGIN
    CREATE TABLE AKTBLPTSTRA (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        TRANSFER_ID BIGINT NOT NULL,
        CARRIER_LABEL NVARCHAR(100) NULL,          -- Bu carrier'ın barkod numarası (20 karakter)
        PARENT_CARRIER_LABEL NVARCHAR(100) NULL,   -- Üst carrier'ın barkodu (NULL ise root level)
        CONTAINER_TYPE NVARCHAR(10) NULL,           -- P:Palet, C:Koli, S:Bağ, B:Koli içi kutu, E:Küçük bağ
        CARRIER_LEVEL INT NULL,                     -- Hiyerarşi seviyesi (1:Palet, 2:Koli, 3:Alt koli, vb.)
        GTIN NVARCHAR(50) NULL,                     -- Ürün GTIN kodu
        SERIAL_NUMBER NVARCHAR(100) NULL,           -- Ürün seri numarası (ürün varsa dolu)
        LOT_NUMBER NVARCHAR(50) NULL,               -- Lot numarası
        EXPIRATION_DATE DATE NULL,                  -- Son kullanma tarihi
        PRODUCTION_DATE DATE NULL,                  -- Üretim tarihi
        PO_NUMBER NVARCHAR(50) NULL,                -- Sipariş numarası
        CREATED_DATE DATETIME DEFAULT GETDATE()
    )
    
    -- Index'ler
    CREATE INDEX IX_AKTBLPTSTRA_TRANSFER_ID ON AKTBLPTSTRA(TRANSFER_ID)
    CREATE INDEX IX_AKTBLPTSTRA_CARRIER_LABEL ON AKTBLPTSTRA(CARRIER_LABEL)
    CREATE INDEX IX_AKTBLPTSTRA_PARENT_CARRIER_LABEL ON AKTBLPTSTRA(PARENT_CARRIER_LABEL)
    CREATE INDEX IX_AKTBLPTSTRA_GTIN ON AKTBLPTSTRA(GTIN)
    CREATE INDEX IX_AKTBLPTSTRA_SERIAL_NUMBER ON AKTBLPTSTRA(SERIAL_NUMBER)
    CREATE INDEX IX_AKTBLPTSTRA_EXPIRATION_DATE ON AKTBLPTSTRA(EXPIRATION_DATE)
    
    -- Foreign Key
    ALTER TABLE AKTBLPTSTRA
    ADD CONSTRAINT FK_AKTBLPTSTRA_TRANSFER_ID 
    FOREIGN KEY (TRANSFER_ID) REFERENCES AKTBLPTSMAS(TRANSFER_ID)
    
    PRINT 'AKTBLPTSTRA tablosu oluşturuldu'
END
ELSE
BEGIN
    PRINT 'AKTBLPTSTRA tablosu zaten mevcut'
END
GO

PRINT 'PTS Tabloları hazır'
GO

