-- AKTBLKULLANICI - Kullanıcı Tablosu
-- Veritabanı: NETSIS

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='AKTBLKULLANICI' AND xtype='U')
BEGIN
    CREATE TABLE AKTBLKULLANICI (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        KULLANICI_ADI NVARCHAR(50) NOT NULL UNIQUE,
        SIFRE NVARCHAR(255) NOT NULL,
        AD_SOYAD NVARCHAR(100),
        EMAIL NVARCHAR(100),
        ROL NVARCHAR(20) DEFAULT 'user',
        DEPARTMAN NVARCHAR(50),
        AKTIF BIT DEFAULT 1,
        SON_GIRIS DATETIME,
        OLUSTURMA_TARIHI DATETIME DEFAULT GETDATE()
    );
    
    PRINT '✅ AKTBLKULLANICI tablosu oluşturuldu';
END
ELSE
BEGIN
    PRINT '✅ AKTBLKULLANICI tablosu zaten mevcut';
END

-- Varsayılan admin kullanıcısı ekle
IF NOT EXISTS (SELECT * FROM AKTBLKULLANICI WHERE KULLANICI_ADI = 'admin')
BEGIN
    INSERT INTO AKTBLKULLANICI (KULLANICI_ADI, SIFRE, AD_SOYAD, EMAIL, ROL, DEPARTMAN, AKTIF)
    VALUES ('admin', 'admin123', 'Admin Kullanıcı', 'admin@atakodits.com', 'admin', 'Yönetim', 1);
    
    PRINT '✅ Varsayılan admin kullanıcısı oluşturuldu';
END

-- Demo kullanıcı ekle
IF NOT EXISTS (SELECT * FROM AKTBLKULLANICI WHERE KULLANICI_ADI = 'demo')
BEGIN
    INSERT INTO AKTBLKULLANICI (KULLANICI_ADI, SIFRE, AD_SOYAD, EMAIL, ROL, DEPARTMAN, AKTIF)
    VALUES ('demo', 'demo123', 'Demo Kullanıcı', 'demo@atakodits.com', 'user', 'Satış', 1);
    
    PRINT '✅ Demo kullanıcısı oluşturuldu';
END

GO

-- AKTBLAYAR - Ayarlar Tablosu
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='AKTBLAYAR' AND xtype='U')
BEGIN
    CREATE TABLE AKTBLAYAR (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        AYAR_ADI NVARCHAR(100) NOT NULL UNIQUE,
        AYAR_DEGERI NVARCHAR(500),
        ACIKLAMA NVARCHAR(200),
        GUNCELLEME_TARIHI DATETIME DEFAULT GETDATE()
    );
    
    PRINT '✅ AKTBLAYAR tablosu oluşturuldu';
END
ELSE
BEGIN
    PRINT '✅ AKTBLAYAR tablosu zaten mevcut';
END

-- Varsayılan ayarları ekle
IF NOT EXISTS (SELECT * FROM AKTBLAYAR WHERE AYAR_ADI = 'urunBarkodBilgisi')
BEGIN
    INSERT INTO AKTBLAYAR (AYAR_ADI, AYAR_DEGERI, ACIKLAMA) VALUES 
    ('urunBarkodBilgisi', 'STOK_KODU', 'Ürün barkod bilgisi alanı');
END

IF NOT EXISTS (SELECT * FROM AKTBLAYAR WHERE AYAR_ADI = 'urunItsBilgisi')
BEGIN
    INSERT INTO AKTBLAYAR (AYAR_ADI, AYAR_DEGERI, ACIKLAMA) VALUES 
    ('urunItsBilgisi', 'TBLSTSABIT.KOD_5=''BESERI''', 'ITS ürün filtresi');
END

IF NOT EXISTS (SELECT * FROM AKTBLAYAR WHERE AYAR_ADI = 'urunUtsBilgisi')
BEGIN
    INSERT INTO AKTBLAYAR (AYAR_ADI, AYAR_DEGERI, ACIKLAMA) VALUES 
    ('urunUtsBilgisi', 'TBLSTSABIT.KOD_5=''UTS''', 'UTS ürün filtresi');
END

IF NOT EXISTS (SELECT * FROM AKTBLAYAR WHERE AYAR_ADI = 'cariGlnBilgisi')
BEGIN
    INSERT INTO AKTBLAYAR (AYAR_ADI, AYAR_DEGERI, ACIKLAMA) VALUES 
    ('cariGlnBilgisi', 'TBLCASABIT.EMAIL', 'Cari GLN bilgisi alanı');
END

IF NOT EXISTS (SELECT * FROM AKTBLAYAR WHERE AYAR_ADI = 'cariUtsBilgisi')
BEGIN
    INSERT INTO AKTBLAYAR (AYAR_ADI, AYAR_DEGERI, ACIKLAMA) VALUES 
    ('cariUtsBilgisi', 'TBLCASABITEK.KULL3S', 'Cari UTS bilgisi alanı');
END

PRINT '✅ Varsayılan ayarlar eklendi';

GO
