-- TRANSFER_ID sütunlarını BIGINT'ten NVARCHAR(50)'ye dönüştür

-- Önce foreign key constraint'i kaldır
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_AKTBLPTSTRA_TRANSFER_ID')
BEGIN
    ALTER TABLE AKTBLPTSTRA DROP CONSTRAINT FK_AKTBLPTSTRA_TRANSFER_ID
    PRINT 'Foreign key silindi'
END
GO

-- Unique index'i kaldır
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_AKTBLPTSMAS_TRANSFER_ID')
BEGIN
    DROP INDEX IX_AKTBLPTSMAS_TRANSFER_ID ON AKTBLPTSMAS
    PRINT 'Unique index silindi'
END
GO

-- Normal index'i kaldır
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_AKTBLPTSTRA_TRANSFER_ID')
BEGIN
    DROP INDEX IX_AKTBLPTSTRA_TRANSFER_ID ON AKTBLPTSTRA
    PRINT 'Transaction index silindi'
END
GO

-- AKTBLPTSMAS tablosundaki TRANSFER_ID'yi değiştir
ALTER TABLE AKTBLPTSMAS 
ALTER COLUMN TRANSFER_ID NVARCHAR(50) NOT NULL
PRINT 'AKTBLPTSMAS.TRANSFER_ID NVARCHAR(50) olarak güncellendi'
GO

-- AKTBLPTSTRA tablosundaki TRANSFER_ID'yi değiştir
ALTER TABLE AKTBLPTSTRA 
ALTER COLUMN TRANSFER_ID NVARCHAR(50) NOT NULL
PRINT 'AKTBLPTSTRA.TRANSFER_ID NVARCHAR(50) olarak güncellendi'
GO

-- Index'leri yeniden oluştur
CREATE UNIQUE INDEX IX_AKTBLPTSMAS_TRANSFER_ID ON AKTBLPTSMAS(TRANSFER_ID)
PRINT 'Unique index yeniden oluşturuldu'
GO

CREATE INDEX IX_AKTBLPTSTRA_TRANSFER_ID ON AKTBLPTSTRA(TRANSFER_ID)
PRINT 'Transaction index yeniden oluşturuldu'
GO

-- Foreign key'i yeniden ekle
ALTER TABLE AKTBLPTSTRA
ADD CONSTRAINT FK_AKTBLPTSTRA_TRANSFER_ID 
FOREIGN KEY (TRANSFER_ID) REFERENCES AKTBLPTSMAS(TRANSFER_ID)
PRINT 'Foreign key yeniden oluşturuldu'
GO

PRINT '✅ TRANSFER_ID sütunları NVARCHAR(50) tipine başarıyla dönüştürüldü'
GO



