// Decompiled with JetBrains decompiler
// Type: NetProITS.FrmAyarlar
// Assembly: NetProITS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 64902309-711B-4AE1-AFF6-78FB4B0E99F7
// Assembly location: C:\Dosyalar\Müşteriler\Afyon Şifa\NetProITS\NetProITS\NetProITS.exe

using DevExpress.XtraBars.Navigation;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using NetProITS.Properties;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace NetProITS
{
  public class FrmAyarlar : Form
  {
    private IContainer components = (IContainer) null;
    private GridView gridView1;
    private NavigationPage navGenelAyarlar;
    private Button btnKaydet;
    private GroupControl groupControl2;
    private TextEdit txtEczSifre2;
    private LabelControl labelControl9;
    private TextEdit txtEczKullanici2;
    private LabelControl labelControl10;
    private TextEdit txtEczGlnNo2;
    private LabelControl labelControl11;
    private TextEdit txtEczAdi2;
    private LabelControl labelControl12;
    private GroupControl groupControl1;
    private TextEdit txtEczSifre1;
    private LabelControl labelControl7;
    private TextEdit txtEczKullanici1;
    private LabelControl labelControl8;
    private TextEdit txtEczGlnNo1;
    private LabelControl labelControl6;
    private TextEdit txtEczAdi1;
    private LabelControl labelControl5;
    private CheckEdit chkBeseri;
    private TextEdit txtDeaktivasyon;
    private LabelControl labelControl4;
    private TextEdit txtSifre;
    private LabelControl labelControl3;
    private TextEdit txtKullaniciAdi;
    private LabelControl labelControl1;
    private TextEdit txtGlnNo;
    private LabelControl labelControl2;
    private NavigationPane navigationPane1;
    private TextEdit txtNetsisSifre;
    private LabelControl labelControl15;
    private TextEdit txtNetsisUser;
    private LabelControl labelControl14;
    private TextEdit txtNetsisSirket;
    private LabelControl labelControl13;
    private TextEdit txtSipDizayNo;
    private LabelControl labelControl17;
    private TextEdit txtFatDizaynNo;
    private LabelControl labelControl16;
    private TextEdit txtSifre2;
    private LabelControl labelControl18;
    private TextEdit txtKullaniciAdi2;
    private LabelControl labelControl19;
    private TextEdit txtGlnNo2;
    private LabelControl labelControl20;
    private TextEdit txtGayriResmiSeri;
    private TextEdit txtResmiEvrakSeri;
    private TextEdit txtGFatDizaynNo;
    private LabelControl labelControl21;
    private GroupControl groupControl3;
    private TextEdit txtEczSifre3;
    private LabelControl labelControl22;
    private TextEdit txtEczKullanici3;
    private LabelControl labelControl23;
    private TextEdit txtEczGlnNo3;
    private LabelControl labelControl24;
    private TextEdit txtEczAdi3;
    private LabelControl labelControl25;
    private TextEdit txtAlisIrsSeri;
    private LabelControl labelControl26;
    private TextEdit txtKosulKodu;
    private LabelControl labelControl27;

    public FrmAyarlar() => this.InitializeComponent();

    private void btnKaydet_Click(object sender, EventArgs e)
    {
      try
      {
        MyUtils.SetParamValue("GlnNo", this.txtGlnNo.Text);
        MyUtils.SetParamValue("KullaniciAdi", this.txtKullaniciAdi.Text);
        MyUtils.SetParamValue("Sifre", this.txtSifre.Text);
        MyUtils.SetParamValue("GlnNo2", this.txtGlnNo2.Text);
        MyUtils.SetParamValue("KullaniciAdi2", this.txtKullaniciAdi2.Text);
        MyUtils.SetParamValue("Sifre2", this.txtSifre2.Text);
        MyUtils.SetParamValue("Deaktivasyon", this.txtDeaktivasyon.Text);
        MyUtils.SetParamValue("Eczane1", this.txtEczAdi1.Text);
        MyUtils.SetParamValue("Eczane2", this.txtEczAdi2.Text);
        MyUtils.SetParamValue("Eczane3", this.txtEczAdi3.Text);
        MyUtils.SetParamValue("EczGlnNo1", this.txtEczGlnNo1.Text);
        MyUtils.SetParamValue("EczGlnNo2", this.txtEczGlnNo2.Text);
        MyUtils.SetParamValue("EczGlnNo3", this.txtEczGlnNo3.Text);
        MyUtils.SetParamValue("EczKullanici1", this.txtEczKullanici1.Text);
        MyUtils.SetParamValue("EczKullanici2", this.txtEczKullanici2.Text);
        MyUtils.SetParamValue("EczKullanici3", this.txtEczKullanici3.Text);
        MyUtils.SetParamValue("EczSifre1", this.txtEczSifre1.Text);
        MyUtils.SetParamValue("EczSifre2", this.txtEczSifre2.Text);
        MyUtils.SetParamValue("EczSifre3", this.txtEczSifre3.Text);
        MyUtils.SetParamValue("IsBeseri", this.chkBeseri.Checked.ToString());
        MyUtils.SetParamValue("NetsisSirket", this.txtNetsisSirket.Text);
        MyUtils.SetParamValue("NetsisUser", this.txtNetsisUser.Text);
        MyUtils.SetParamValue("NetsisPass", this.txtNetsisSifre.Text);
        MyUtils.SetParamValue("FaturaDizaynNo", this.txtFatDizaynNo.Text);
        MyUtils.SetParamValue("GayriFaturaDizaynNo", this.txtGFatDizaynNo.Text);
        MyUtils.SetParamValue("ResmiEvrakSeri", this.txtResmiEvrakSeri.Text);
        MyUtils.SetParamValue("GayriEvrakSeri", this.txtGayriResmiSeri.Text);
        MyUtils.SetParamValue("SiparisDizaynNo", this.txtSipDizayNo.Text);
        MyUtils.SetParamValue("AlisIrsaliyeSeri", this.txtAlisIrsSeri.Text);
        int num = (int) MessageBox.Show("Kayıt yapılmıştır.");
      }
      catch (Exception ex)
      {
        int num = (int) MessageBox.Show("Hata oluştu:" + ex.Message);
      }
    }

    private void FrmAyarlar_Load(object sender, EventArgs e)
    {
      try
      {
        this.txtGlnNo.Text = MyUtils.GetParamValue("GlnNo");
        this.txtKullaniciAdi.Text = MyUtils.GetParamValue("KullaniciAdi");
        this.txtSifre.Text = MyUtils.GetParamValue("Sifre");
        this.txtGlnNo2.Text = MyUtils.GetParamValue("GlnNo2");
        this.txtKullaniciAdi2.Text = MyUtils.GetParamValue("KullaniciAdi2");
        this.txtSifre2.Text = MyUtils.GetParamValue("Sifre2");
        this.txtDeaktivasyon.Text = MyUtils.GetParamValue("Deaktivasyon");
        this.txtEczAdi1.Text = MyUtils.GetParamValue("Eczane1");
        this.txtEczAdi2.Text = MyUtils.GetParamValue("Eczane2");
        this.txtEczAdi3.Text = MyUtils.GetParamValue("Eczane3");
        this.txtEczGlnNo1.Text = MyUtils.GetParamValue("EczGlnNo1");
        this.txtEczGlnNo2.Text = MyUtils.GetParamValue("EczGlnNo2");
        this.txtEczGlnNo3.Text = MyUtils.GetParamValue("EczGlnNo3");
        this.txtEczKullanici1.Text = MyUtils.GetParamValue("EczKullanici1");
        this.txtEczKullanici2.Text = MyUtils.GetParamValue("EczKullanici2");
        this.txtEczKullanici3.Text = MyUtils.GetParamValue("EczKullanici3");
        this.txtEczSifre1.Text = MyUtils.GetParamValue("EczSifre1");
        this.txtEczSifre2.Text = MyUtils.GetParamValue("EczSifre2");
        this.txtEczSifre3.Text = MyUtils.GetParamValue("EczSifre3");
        this.txtNetsisSirket.Text = MyUtils.GetParamValue("NetsisSirket");
        this.txtNetsisUser.Text = MyUtils.GetParamValue("NetsisUser");
        this.txtNetsisSifre.Text = MyUtils.GetParamValue("NetsisPass");
        this.txtFatDizaynNo.Text = MyUtils.GetParamValue("FaturaDizaynNo");
        this.txtSipDizayNo.Text = MyUtils.GetParamValue("SiparisDizaynNo");
        this.txtGFatDizaynNo.Text = MyUtils.GetParamValue("GayriFaturaDizaynNo");
        this.txtResmiEvrakSeri.Text = MyUtils.GetParamValue("ResmiEvrakSeri");
        this.txtGayriResmiSeri.Text = MyUtils.GetParamValue("GayriEvrakSeri");
        this.txtAlisIrsSeri.Text = MyUtils.GetParamValue("AlisIrsaliyeSeri");
        this.chkBeseri.Checked = !string.IsNullOrEmpty(MyUtils.GetParamValue("IsBeseri")) && Convert.ToBoolean(MyUtils.GetParamValue("IsBeseri"));
      }
      catch (Exception ex)
      {
        int num = (int) MessageBox.Show("Hata oluştu:" + ex.Message);
      }
    }

    private void btnYeni_Click(object sender, EventArgs e)
    {
    }

    private void btnSil_Click(object sender, EventArgs e)
    {
    }

    private void btnSepetKaydet_Click(object sender, EventArgs e)
    {
    }

    private void btnYazdir_Click(object sender, EventArgs e)
    {
    }

    private void grdListe_DoubleClick(object sender, EventArgs e)
    {
    }

    private void btnTasarim_Click(object sender, EventArgs e)
    {
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (FrmAyarlar));
      this.gridView1 = new GridView();
      this.navGenelAyarlar = new NavigationPage();
      this.txtKosulKodu = new TextEdit();
      this.labelControl27 = new LabelControl();
      this.txtAlisIrsSeri = new TextEdit();
      this.labelControl26 = new LabelControl();
      this.groupControl3 = new GroupControl();
      this.txtEczSifre3 = new TextEdit();
      this.labelControl22 = new LabelControl();
      this.txtEczKullanici3 = new TextEdit();
      this.labelControl23 = new LabelControl();
      this.txtEczGlnNo3 = new TextEdit();
      this.labelControl24 = new LabelControl();
      this.txtEczAdi3 = new TextEdit();
      this.labelControl25 = new LabelControl();
      this.txtGayriResmiSeri = new TextEdit();
      this.txtResmiEvrakSeri = new TextEdit();
      this.txtGFatDizaynNo = new TextEdit();
      this.labelControl21 = new LabelControl();
      this.txtSifre2 = new TextEdit();
      this.labelControl18 = new LabelControl();
      this.txtKullaniciAdi2 = new TextEdit();
      this.labelControl19 = new LabelControl();
      this.txtGlnNo2 = new TextEdit();
      this.labelControl20 = new LabelControl();
      this.txtSipDizayNo = new TextEdit();
      this.labelControl17 = new LabelControl();
      this.txtFatDizaynNo = new TextEdit();
      this.labelControl16 = new LabelControl();
      this.txtNetsisSifre = new TextEdit();
      this.labelControl15 = new LabelControl();
      this.txtNetsisUser = new TextEdit();
      this.labelControl14 = new LabelControl();
      this.txtNetsisSirket = new TextEdit();
      this.labelControl13 = new LabelControl();
      this.btnKaydet = new Button();
      this.groupControl2 = new GroupControl();
      this.txtEczSifre2 = new TextEdit();
      this.labelControl9 = new LabelControl();
      this.txtEczKullanici2 = new TextEdit();
      this.labelControl10 = new LabelControl();
      this.txtEczGlnNo2 = new TextEdit();
      this.labelControl11 = new LabelControl();
      this.txtEczAdi2 = new TextEdit();
      this.labelControl12 = new LabelControl();
      this.groupControl1 = new GroupControl();
      this.txtEczSifre1 = new TextEdit();
      this.labelControl7 = new LabelControl();
      this.txtEczKullanici1 = new TextEdit();
      this.labelControl8 = new LabelControl();
      this.txtEczGlnNo1 = new TextEdit();
      this.labelControl6 = new LabelControl();
      this.txtEczAdi1 = new TextEdit();
      this.labelControl5 = new LabelControl();
      this.chkBeseri = new CheckEdit();
      this.txtDeaktivasyon = new TextEdit();
      this.labelControl4 = new LabelControl();
      this.txtSifre = new TextEdit();
      this.labelControl3 = new LabelControl();
      this.txtKullaniciAdi = new TextEdit();
      this.labelControl1 = new LabelControl();
      this.txtGlnNo = new TextEdit();
      this.labelControl2 = new LabelControl();
      this.navigationPane1 = new NavigationPane();
      this.gridView1.BeginInit();
      this.navGenelAyarlar.SuspendLayout();
      this.txtKosulKodu.Properties.BeginInit();
      this.txtAlisIrsSeri.Properties.BeginInit();
      this.groupControl3.BeginInit();
      this.groupControl3.SuspendLayout();
      this.txtEczSifre3.Properties.BeginInit();
      this.txtEczKullanici3.Properties.BeginInit();
      this.txtEczGlnNo3.Properties.BeginInit();
      this.txtEczAdi3.Properties.BeginInit();
      this.txtGayriResmiSeri.Properties.BeginInit();
      this.txtResmiEvrakSeri.Properties.BeginInit();
      this.txtGFatDizaynNo.Properties.BeginInit();
      this.txtSifre2.Properties.BeginInit();
      this.txtKullaniciAdi2.Properties.BeginInit();
      this.txtGlnNo2.Properties.BeginInit();
      this.txtSipDizayNo.Properties.BeginInit();
      this.txtFatDizaynNo.Properties.BeginInit();
      this.txtNetsisSifre.Properties.BeginInit();
      this.txtNetsisUser.Properties.BeginInit();
      this.txtNetsisSirket.Properties.BeginInit();
      this.groupControl2.BeginInit();
      this.groupControl2.SuspendLayout();
      this.txtEczSifre2.Properties.BeginInit();
      this.txtEczKullanici2.Properties.BeginInit();
      this.txtEczGlnNo2.Properties.BeginInit();
      this.txtEczAdi2.Properties.BeginInit();
      this.groupControl1.BeginInit();
      this.groupControl1.SuspendLayout();
      this.txtEczSifre1.Properties.BeginInit();
      this.txtEczKullanici1.Properties.BeginInit();
      this.txtEczGlnNo1.Properties.BeginInit();
      this.txtEczAdi1.Properties.BeginInit();
      this.chkBeseri.Properties.BeginInit();
      this.txtDeaktivasyon.Properties.BeginInit();
      this.txtSifre.Properties.BeginInit();
      this.txtKullaniciAdi.Properties.BeginInit();
      this.txtGlnNo.Properties.BeginInit();
      ((ISupportInitialize) this.navigationPane1).BeginInit();
      this.navigationPane1.SuspendLayout();
      this.SuspendLayout();
      this.gridView1.Name = "gridView1";
      this.navGenelAyarlar.Caption = "Genel Ayarlar";
      this.navGenelAyarlar.Controls.Add((Control) this.txtKosulKodu);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl27);
      this.navGenelAyarlar.Controls.Add((Control) this.txtAlisIrsSeri);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl26);
      this.navGenelAyarlar.Controls.Add((Control) this.groupControl3);
      this.navGenelAyarlar.Controls.Add((Control) this.txtGayriResmiSeri);
      this.navGenelAyarlar.Controls.Add((Control) this.txtResmiEvrakSeri);
      this.navGenelAyarlar.Controls.Add((Control) this.txtGFatDizaynNo);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl21);
      this.navGenelAyarlar.Controls.Add((Control) this.txtSifre2);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl18);
      this.navGenelAyarlar.Controls.Add((Control) this.txtKullaniciAdi2);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl19);
      this.navGenelAyarlar.Controls.Add((Control) this.txtGlnNo2);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl20);
      this.navGenelAyarlar.Controls.Add((Control) this.txtSipDizayNo);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl17);
      this.navGenelAyarlar.Controls.Add((Control) this.txtFatDizaynNo);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl16);
      this.navGenelAyarlar.Controls.Add((Control) this.txtNetsisSifre);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl15);
      this.navGenelAyarlar.Controls.Add((Control) this.txtNetsisUser);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl14);
      this.navGenelAyarlar.Controls.Add((Control) this.txtNetsisSirket);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl13);
      this.navGenelAyarlar.Controls.Add((Control) this.btnKaydet);
      this.navGenelAyarlar.Controls.Add((Control) this.groupControl2);
      this.navGenelAyarlar.Controls.Add((Control) this.groupControl1);
      this.navGenelAyarlar.Controls.Add((Control) this.chkBeseri);
      this.navGenelAyarlar.Controls.Add((Control) this.txtDeaktivasyon);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl4);
      this.navGenelAyarlar.Controls.Add((Control) this.txtSifre);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl3);
      this.navGenelAyarlar.Controls.Add((Control) this.txtKullaniciAdi);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl1);
      this.navGenelAyarlar.Controls.Add((Control) this.txtGlnNo);
      this.navGenelAyarlar.Controls.Add((Control) this.labelControl2);
      this.navGenelAyarlar.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.navGenelAyarlar.Name = "navGenelAyarlar";
      this.navGenelAyarlar.PageText = "Genel Ayarlar";
      this.navGenelAyarlar.Properties.AppearanceCaption.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.navGenelAyarlar.Properties.AppearanceCaption.Image = (Image) componentResourceManager.GetObject("navGenelAyarlar.Properties.AppearanceCaption.Image");
      this.navGenelAyarlar.Properties.AppearanceCaption.Options.UseFont = true;
      this.navGenelAyarlar.Properties.AppearanceCaption.Options.UseImage = true;
      this.navGenelAyarlar.Size = new Size(684, 758);
      this.txtKosulKodu.Location = new Point(129, 224);
      this.txtKosulKodu.Name = "txtKosulKodu";
      this.txtKosulKodu.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtKosulKodu.Properties.Appearance.Options.UseFont = true;
      this.txtKosulKodu.Size = new Size(207, 30);
      this.txtKosulKodu.TabIndex = 41;
      this.txtKosulKodu.Visible = false;
      this.labelControl27.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl27.Appearance.Options.UseFont = true;
      this.labelControl27.Location = new Point(17, 227);
      this.labelControl27.Name = "labelControl27";
      this.labelControl27.Size = new Size(104, 19);
      this.labelControl27.TabIndex = 40;
      this.labelControl27.Text = "MF Koşul Kodu";
      this.labelControl27.Visible = false;
      this.txtAlisIrsSeri.Location = new Point(489, 221);
      this.txtAlisIrsSeri.Name = "txtAlisIrsSeri";
      this.txtAlisIrsSeri.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtAlisIrsSeri.Properties.Appearance.Options.UseFont = true;
      this.txtAlisIrsSeri.Size = new Size(98, 30);
      this.txtAlisIrsSeri.TabIndex = 39;
      this.labelControl26.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl26.Appearance.Options.UseFont = true;
      this.labelControl26.Location = new Point(345, 227);
      this.labelControl26.Name = "labelControl26";
      this.labelControl26.Size = new Size(125, 19);
      this.labelControl26.TabIndex = 38;
      this.labelControl26.Text = "Alış İrsaliyesi Seri";
      this.groupControl3.Controls.Add((Control) this.txtEczSifre3);
      this.groupControl3.Controls.Add((Control) this.labelControl22);
      this.groupControl3.Controls.Add((Control) this.txtEczKullanici3);
      this.groupControl3.Controls.Add((Control) this.labelControl23);
      this.groupControl3.Controls.Add((Control) this.txtEczGlnNo3);
      this.groupControl3.Controls.Add((Control) this.labelControl24);
      this.groupControl3.Controls.Add((Control) this.txtEczAdi3);
      this.groupControl3.Controls.Add((Control) this.labelControl25);
      this.groupControl3.Location = new Point(18, 553);
      this.groupControl3.Name = "groupControl3";
      this.groupControl3.Size = new Size(597, 140);
      this.groupControl3.TabIndex = 37;
      this.groupControl3.Text = "3.Eczane";
      this.txtEczSifre3.Location = new Point(384, 80);
      this.txtEczSifre3.Name = "txtEczSifre3";
      this.txtEczSifre3.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczSifre3.Properties.Appearance.Options.UseFont = true;
      this.txtEczSifre3.Properties.PasswordChar = '*';
      this.txtEczSifre3.Size = new Size(207, 26);
      this.txtEczSifre3.TabIndex = 15;
      this.labelControl22.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl22.Appearance.Options.UseFont = true;
      this.labelControl22.Location = new Point(336, 83);
      this.labelControl22.Name = "labelControl22";
      this.labelControl22.Size = new Size(32, 19);
      this.labelControl22.TabIndex = 14;
      this.labelControl22.Text = "Şifre";
      this.txtEczKullanici3.Location = new Point(122, 80);
      this.txtEczKullanici3.Name = "txtEczKullanici3";
      this.txtEczKullanici3.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczKullanici3.Properties.Appearance.Options.UseFont = true;
      this.txtEczKullanici3.Size = new Size(207, 26);
      this.txtEczKullanici3.TabIndex = 13;
      this.labelControl23.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl23.Appearance.Options.UseFont = true;
      this.labelControl23.Location = new Point(11, 83);
      this.labelControl23.Name = "labelControl23";
      this.labelControl23.Size = new Size(83, 19);
      this.labelControl23.TabIndex = 12;
      this.labelControl23.Text = "Kullancı Adı";
      this.txtEczGlnNo3.Location = new Point(122, 52);
      this.txtEczGlnNo3.Name = "txtEczGlnNo3";
      this.txtEczGlnNo3.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczGlnNo3.Properties.Appearance.Options.UseFont = true;
      this.txtEczGlnNo3.Size = new Size(207, 26);
      this.txtEczGlnNo3.TabIndex = 11;
      this.labelControl24.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl24.Appearance.Options.UseFont = true;
      this.labelControl24.Location = new Point(11, 55);
      this.labelControl24.Name = "labelControl24";
      this.labelControl24.Size = new Size(49, 19);
      this.labelControl24.TabIndex = 10;
      this.labelControl24.Text = "Gln No";
      this.txtEczAdi3.Location = new Point(122, 24);
      this.txtEczAdi3.Name = "txtEczAdi3";
      this.txtEczAdi3.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczAdi3.Properties.Appearance.Options.UseFont = true;
      this.txtEczAdi3.Size = new Size(353, 26);
      this.txtEczAdi3.TabIndex = 9;
      this.labelControl25.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl25.Appearance.Options.UseFont = true;
      this.labelControl25.Location = new Point(11, 30);
      this.labelControl25.Name = "labelControl25";
      this.labelControl25.Size = new Size(77, 19);
      this.labelControl25.TabIndex = 8;
      this.labelControl25.Text = "Eczane Adı";
      this.txtGayriResmiSeri.Location = new Point(591, 156);
      this.txtGayriResmiSeri.Name = "txtGayriResmiSeri";
      this.txtGayriResmiSeri.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtGayriResmiSeri.Properties.Appearance.Options.UseFont = true;
      this.txtGayriResmiSeri.Size = new Size(68, 30);
      this.txtGayriResmiSeri.TabIndex = 36;
      this.txtResmiEvrakSeri.Location = new Point(591, 124);
      this.txtResmiEvrakSeri.Name = "txtResmiEvrakSeri";
      this.txtResmiEvrakSeri.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtResmiEvrakSeri.Properties.Appearance.Options.UseFont = true;
      this.txtResmiEvrakSeri.Size = new Size(68, 30);
      this.txtResmiEvrakSeri.TabIndex = 35;
      this.txtGFatDizaynNo.Location = new Point(489, 156);
      this.txtGFatDizaynNo.Name = "txtGFatDizaynNo";
      this.txtGFatDizaynNo.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtGFatDizaynNo.Properties.Appearance.Options.UseFont = true;
      this.txtGFatDizaynNo.Size = new Size(98, 30);
      this.txtGFatDizaynNo.TabIndex = 34;
      this.labelControl21.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl21.Appearance.Options.UseFont = true;
      this.labelControl21.Location = new Point(345, 162);
      this.labelControl21.Name = "labelControl21";
      this.labelControl21.Size = new Size(137, 19);
      this.labelControl21.TabIndex = 33;
      this.labelControl21.Text = "G.Fatura Dizayn No";
      this.txtSifre2.Location = new Point(454, 80);
      this.txtSifre2.Name = "txtSifre2";
      this.txtSifre2.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtSifre2.Properties.Appearance.Options.UseFont = true;
      this.txtSifre2.Properties.PasswordChar = '*';
      this.txtSifre2.Size = new Size(207, 30);
      this.txtSifre2.TabIndex = 32;
      this.labelControl18.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl18.Appearance.Options.UseFont = true;
      this.labelControl18.Location = new Point(343, 86);
      this.labelControl18.Name = "labelControl18";
      this.labelControl18.Size = new Size(46, 19);
      this.labelControl18.TabIndex = 31;
      this.labelControl18.Text = "Şifre 2";
      this.txtKullaniciAdi2.Location = new Point(454, 47);
      this.txtKullaniciAdi2.Name = "txtKullaniciAdi2";
      this.txtKullaniciAdi2.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtKullaniciAdi2.Properties.Appearance.Options.UseFont = true;
      this.txtKullaniciAdi2.Size = new Size(207, 30);
      this.txtKullaniciAdi2.TabIndex = 30;
      this.labelControl19.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl19.Appearance.Options.UseFont = true;
      this.labelControl19.Location = new Point(343, 53);
      this.labelControl19.Name = "labelControl19";
      this.labelControl19.Size = new Size(97, 19);
      this.labelControl19.TabIndex = 29;
      this.labelControl19.Text = "Kullancı Adı 2";
      this.txtGlnNo2.Location = new Point(454, 14);
      this.txtGlnNo2.Name = "txtGlnNo2";
      this.txtGlnNo2.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtGlnNo2.Properties.Appearance.Options.UseFont = true;
      this.txtGlnNo2.Size = new Size(207, 30);
      this.txtGlnNo2.TabIndex = 28;
      this.labelControl20.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl20.Appearance.Options.UseFont = true;
      this.labelControl20.Location = new Point(343, 20);
      this.labelControl20.Name = "labelControl20";
      this.labelControl20.Size = new Size(63, 19);
      this.labelControl20.TabIndex = 27;
      this.labelControl20.Text = "Gln No 2";
      this.txtSipDizayNo.Location = new Point(489, 188);
      this.txtSipDizayNo.Name = "txtSipDizayNo";
      this.txtSipDizayNo.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtSipDizayNo.Properties.Appearance.Options.UseFont = true;
      this.txtSipDizayNo.Size = new Size(98, 30);
      this.txtSipDizayNo.TabIndex = 26;
      this.labelControl17.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl17.Appearance.Options.UseFont = true;
      this.labelControl17.Location = new Point(345, 194);
      this.labelControl17.Name = "labelControl17";
      this.labelControl17.Size = new Size(124, 19);
      this.labelControl17.TabIndex = 25;
      this.labelControl17.Text = "Sipariş Dizayn No";
      this.txtFatDizaynNo.Location = new Point(489, 124);
      this.txtFatDizaynNo.Name = "txtFatDizaynNo";
      this.txtFatDizaynNo.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtFatDizaynNo.Properties.Appearance.Options.UseFont = true;
      this.txtFatDizaynNo.Size = new Size(98, 30);
      this.txtFatDizaynNo.TabIndex = 24;
      this.labelControl16.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl16.Appearance.Options.UseFont = true;
      this.labelControl16.Location = new Point(345, 130);
      this.labelControl16.Name = "labelControl16";
      this.labelControl16.Size = new Size(131, 19);
      this.labelControl16.TabIndex = 23;
      this.labelControl16.Text = "Res.Fatura Diz. No";
      this.txtNetsisSifre.Location = new Point(129, 190);
      this.txtNetsisSifre.Name = "txtNetsisSifre";
      this.txtNetsisSifre.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtNetsisSifre.Properties.Appearance.Options.UseFont = true;
      this.txtNetsisSifre.Size = new Size(207, 30);
      this.txtNetsisSifre.TabIndex = 22;
      this.txtNetsisSifre.Visible = false;
      this.labelControl15.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl15.Appearance.Options.UseFont = true;
      this.labelControl15.Location = new Point(18, 196);
      this.labelControl15.Name = "labelControl15";
      this.labelControl15.Size = new Size(79, 19);
      this.labelControl15.TabIndex = 21;
      this.labelControl15.Text = "Netsis Şifre";
      this.labelControl15.Visible = false;
      this.txtNetsisUser.Location = new Point(129, 157);
      this.txtNetsisUser.Name = "txtNetsisUser";
      this.txtNetsisUser.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtNetsisUser.Properties.Appearance.Options.UseFont = true;
      this.txtNetsisUser.Size = new Size(207, 30);
      this.txtNetsisUser.TabIndex = 20;
      this.txtNetsisUser.Visible = false;
      this.labelControl14.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl14.Appearance.Options.UseFont = true;
      this.labelControl14.Location = new Point(18, 163);
      this.labelControl14.Name = "labelControl14";
      this.labelControl14.Size = new Size(79, 19);
      this.labelControl14.TabIndex = 19;
      this.labelControl14.Text = "Netsis User";
      this.labelControl14.Visible = false;
      this.txtNetsisSirket.Location = new Point(129, 124);
      this.txtNetsisSirket.Name = "txtNetsisSirket";
      this.txtNetsisSirket.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtNetsisSirket.Properties.Appearance.Options.UseFont = true;
      this.txtNetsisSirket.Size = new Size(207, 30);
      this.txtNetsisSirket.TabIndex = 18;
      this.labelControl13.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl13.Appearance.Options.UseFont = true;
      this.labelControl13.Location = new Point(18, 130);
      this.labelControl13.Name = "labelControl13";
      this.labelControl13.Size = new Size(87, 19);
      this.labelControl13.TabIndex = 17;
      this.labelControl13.Text = "Netsis Şirket";
      this.btnKaydet.Dock = DockStyle.Bottom;
      this.btnKaydet.Font = new Font("Microsoft Sans Serif", 15.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.btnKaydet.Image = (Image) Resources._1311968555_button_ok;
      this.btnKaydet.ImageAlign = ContentAlignment.MiddleLeft;
      this.btnKaydet.Location = new Point(0, 698);
      this.btnKaydet.Name = "btnKaydet";
      this.btnKaydet.Size = new Size(684, 60);
      this.btnKaydet.TabIndex = 16;
      this.btnKaydet.Text = "Kaydet";
      this.btnKaydet.UseVisualStyleBackColor = true;
      this.btnKaydet.Click += new EventHandler(this.btnKaydet_Click);
      this.groupControl2.Controls.Add((Control) this.txtEczSifre2);
      this.groupControl2.Controls.Add((Control) this.labelControl9);
      this.groupControl2.Controls.Add((Control) this.txtEczKullanici2);
      this.groupControl2.Controls.Add((Control) this.labelControl10);
      this.groupControl2.Controls.Add((Control) this.txtEczGlnNo2);
      this.groupControl2.Controls.Add((Control) this.labelControl11);
      this.groupControl2.Controls.Add((Control) this.txtEczAdi2);
      this.groupControl2.Controls.Add((Control) this.labelControl12);
      this.groupControl2.Location = new Point(18, 431);
      this.groupControl2.Name = "groupControl2";
      this.groupControl2.Size = new Size(597, 116);
      this.groupControl2.TabIndex = 15;
      this.groupControl2.Text = "2.Eczane";
      this.txtEczSifre2.Location = new Point(385, 80);
      this.txtEczSifre2.Name = "txtEczSifre2";
      this.txtEczSifre2.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczSifre2.Properties.Appearance.Options.UseFont = true;
      this.txtEczSifre2.Properties.PasswordChar = '*';
      this.txtEczSifre2.Size = new Size(207, 26);
      this.txtEczSifre2.TabIndex = 15;
      this.labelControl9.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl9.Appearance.Options.UseFont = true;
      this.labelControl9.Location = new Point(338, 83);
      this.labelControl9.Name = "labelControl9";
      this.labelControl9.Size = new Size(32, 19);
      this.labelControl9.TabIndex = 14;
      this.labelControl9.Text = "Şifre";
      this.txtEczKullanici2.Location = new Point(122, 80);
      this.txtEczKullanici2.Name = "txtEczKullanici2";
      this.txtEczKullanici2.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczKullanici2.Properties.Appearance.Options.UseFont = true;
      this.txtEczKullanici2.Size = new Size(207, 26);
      this.txtEczKullanici2.TabIndex = 13;
      this.labelControl10.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl10.Appearance.Options.UseFont = true;
      this.labelControl10.Location = new Point(11, 83);
      this.labelControl10.Name = "labelControl10";
      this.labelControl10.Size = new Size(83, 19);
      this.labelControl10.TabIndex = 12;
      this.labelControl10.Text = "Kullancı Adı";
      this.txtEczGlnNo2.Location = new Point(122, 52);
      this.txtEczGlnNo2.Name = "txtEczGlnNo2";
      this.txtEczGlnNo2.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczGlnNo2.Properties.Appearance.Options.UseFont = true;
      this.txtEczGlnNo2.Size = new Size(207, 26);
      this.txtEczGlnNo2.TabIndex = 11;
      this.labelControl11.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl11.Appearance.Options.UseFont = true;
      this.labelControl11.Location = new Point(11, 55);
      this.labelControl11.Name = "labelControl11";
      this.labelControl11.Size = new Size(49, 19);
      this.labelControl11.TabIndex = 10;
      this.labelControl11.Text = "Gln No";
      this.txtEczAdi2.Location = new Point(122, 24);
      this.txtEczAdi2.Name = "txtEczAdi2";
      this.txtEczAdi2.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczAdi2.Properties.Appearance.Options.UseFont = true;
      this.txtEczAdi2.Size = new Size(353, 26);
      this.txtEczAdi2.TabIndex = 9;
      this.labelControl12.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl12.Appearance.Options.UseFont = true;
      this.labelControl12.Location = new Point(11, 30);
      this.labelControl12.Name = "labelControl12";
      this.labelControl12.Size = new Size(77, 19);
      this.labelControl12.TabIndex = 8;
      this.labelControl12.Text = "Eczane Adı";
      this.groupControl1.Controls.Add((Control) this.txtEczSifre1);
      this.groupControl1.Controls.Add((Control) this.labelControl7);
      this.groupControl1.Controls.Add((Control) this.txtEczKullanici1);
      this.groupControl1.Controls.Add((Control) this.labelControl8);
      this.groupControl1.Controls.Add((Control) this.txtEczGlnNo1);
      this.groupControl1.Controls.Add((Control) this.labelControl6);
      this.groupControl1.Controls.Add((Control) this.txtEczAdi1);
      this.groupControl1.Controls.Add((Control) this.labelControl5);
      this.groupControl1.Location = new Point(18, 314);
      this.groupControl1.Name = "groupControl1";
      this.groupControl1.Size = new Size(597, 112);
      this.groupControl1.TabIndex = 14;
      this.groupControl1.Text = "1.Eczane";
      this.txtEczSifre1.Location = new Point(385, 80);
      this.txtEczSifre1.Name = "txtEczSifre1";
      this.txtEczSifre1.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczSifre1.Properties.Appearance.Options.UseFont = true;
      this.txtEczSifre1.Properties.PasswordChar = '*';
      this.txtEczSifre1.Size = new Size(207, 26);
      this.txtEczSifre1.TabIndex = 15;
      this.labelControl7.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl7.Appearance.Options.UseFont = true;
      this.labelControl7.Location = new Point(339, 83);
      this.labelControl7.Name = "labelControl7";
      this.labelControl7.Size = new Size(32, 19);
      this.labelControl7.TabIndex = 14;
      this.labelControl7.Text = "Şifre";
      this.txtEczKullanici1.Location = new Point(122, 80);
      this.txtEczKullanici1.Name = "txtEczKullanici1";
      this.txtEczKullanici1.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczKullanici1.Properties.Appearance.Options.UseFont = true;
      this.txtEczKullanici1.Size = new Size(207, 26);
      this.txtEczKullanici1.TabIndex = 13;
      this.labelControl8.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl8.Appearance.Options.UseFont = true;
      this.labelControl8.Location = new Point(11, 83);
      this.labelControl8.Name = "labelControl8";
      this.labelControl8.Size = new Size(83, 19);
      this.labelControl8.TabIndex = 12;
      this.labelControl8.Text = "Kullancı Adı";
      this.txtEczGlnNo1.Location = new Point(122, 52);
      this.txtEczGlnNo1.Name = "txtEczGlnNo1";
      this.txtEczGlnNo1.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczGlnNo1.Properties.Appearance.Options.UseFont = true;
      this.txtEczGlnNo1.Size = new Size(207, 26);
      this.txtEczGlnNo1.TabIndex = 11;
      this.labelControl6.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl6.Appearance.Options.UseFont = true;
      this.labelControl6.Location = new Point(11, 55);
      this.labelControl6.Name = "labelControl6";
      this.labelControl6.Size = new Size(49, 19);
      this.labelControl6.TabIndex = 10;
      this.labelControl6.Text = "Gln No";
      this.txtEczAdi1.Location = new Point(122, 24);
      this.txtEczAdi1.Name = "txtEczAdi1";
      this.txtEczAdi1.Properties.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtEczAdi1.Properties.Appearance.Options.UseFont = true;
      this.txtEczAdi1.Size = new Size(353, 26);
      this.txtEczAdi1.TabIndex = 9;
      this.labelControl5.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl5.Appearance.Options.UseFont = true;
      this.labelControl5.Location = new Point(11, 30);
      this.labelControl5.Name = "labelControl5";
      this.labelControl5.Size = new Size(77, 19);
      this.labelControl5.TabIndex = 8;
      this.labelControl5.Text = "Eczane Adı";
      this.chkBeseri.Location = new Point(404, 275);
      this.chkBeseri.Name = "chkBeseri";
      this.chkBeseri.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.chkBeseri.Properties.Appearance.Options.UseFont = true;
      this.chkBeseri.Properties.Caption = "Sadece Beşeri";
      this.chkBeseri.Size = new Size(173, 27);
      this.chkBeseri.TabIndex = 12;
      this.txtDeaktivasyon.Location = new Point(191, 274);
      this.txtDeaktivasyon.Name = "txtDeaktivasyon";
      this.txtDeaktivasyon.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtDeaktivasyon.Properties.Appearance.Options.UseFont = true;
      this.txtDeaktivasyon.Size = new Size(207, 30);
      this.txtDeaktivasyon.TabIndex = 11;
      this.labelControl4.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl4.Appearance.Options.UseFont = true;
      this.labelControl4.Location = new Point(18, 280);
      this.labelControl4.Name = "labelControl4";
      this.labelControl4.Size = new Size(167, 19);
      this.labelControl4.TabIndex = 10;
      this.labelControl4.Text = "Deaktivasyon Cari Kodu";
      this.txtSifre.Location = new Point(129, 79);
      this.txtSifre.Name = "txtSifre";
      this.txtSifre.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtSifre.Properties.Appearance.Options.UseFont = true;
      this.txtSifre.Properties.PasswordChar = '*';
      this.txtSifre.Size = new Size(207, 30);
      this.txtSifre.TabIndex = 9;
      this.labelControl3.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl3.Appearance.Options.UseFont = true;
      this.labelControl3.Location = new Point(18, 85);
      this.labelControl3.Name = "labelControl3";
      this.labelControl3.Size = new Size(32, 19);
      this.labelControl3.TabIndex = 8;
      this.labelControl3.Text = "Şifre";
      this.txtKullaniciAdi.Location = new Point(129, 46);
      this.txtKullaniciAdi.Name = "txtKullaniciAdi";
      this.txtKullaniciAdi.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtKullaniciAdi.Properties.Appearance.Options.UseFont = true;
      this.txtKullaniciAdi.Size = new Size(207, 30);
      this.txtKullaniciAdi.TabIndex = 7;
      this.labelControl1.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl1.Appearance.Options.UseFont = true;
      this.labelControl1.Location = new Point(18, 52);
      this.labelControl1.Name = "labelControl1";
      this.labelControl1.Size = new Size(83, 19);
      this.labelControl1.TabIndex = 6;
      this.labelControl1.Text = "Kullancı Adı";
      this.txtGlnNo.Location = new Point(129, 13);
      this.txtGlnNo.Name = "txtGlnNo";
      this.txtGlnNo.Properties.Appearance.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.txtGlnNo.Properties.Appearance.Options.UseFont = true;
      this.txtGlnNo.Size = new Size(207, 30);
      this.txtGlnNo.TabIndex = 5;
      this.labelControl2.Appearance.Font = new Font("Tahoma", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.labelControl2.Appearance.Options.UseFont = true;
      this.labelControl2.Location = new Point(18, 19);
      this.labelControl2.Name = "labelControl2";
      this.labelControl2.Size = new Size(49, 19);
      this.labelControl2.TabIndex = 4;
      this.labelControl2.Text = "Gln No";
      this.navigationPane1.Controls.Add((Control) this.navGenelAyarlar);
      this.navigationPane1.Dock = DockStyle.Fill;
      this.navigationPane1.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.navigationPane1.Location = new Point(0, 0);
      this.navigationPane1.Name = "navigationPane1";
      this.navigationPane1.PageProperties.AppearanceCaption.Font = new Font("Tahoma", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
      this.navigationPane1.PageProperties.AppearanceCaption.Options.UseFont = true;
      this.navigationPane1.Pages.AddRange(new NavigationPageBase[1]
      {
        (NavigationPageBase) this.navGenelAyarlar
      });
      this.navigationPane1.RegularSize = new Size(787, 817);
      this.navigationPane1.SelectedPage = (INavigationPage) this.navGenelAyarlar;
      this.navigationPane1.Size = new Size(787, 817);
      this.navigationPane1.TabIndex = 0;
      this.navigationPane1.Text = "navigationPane1";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(787, 817);
      this.Controls.Add((Control) this.navigationPane1);
      this.Name = nameof (FrmAyarlar);
      this.Text = "Ayarlar";
      this.Load += new EventHandler(this.FrmAyarlar_Load);
      this.gridView1.EndInit();
      this.navGenelAyarlar.ResumeLayout(false);
      this.navGenelAyarlar.PerformLayout();
      this.txtKosulKodu.Properties.EndInit();
      this.txtAlisIrsSeri.Properties.EndInit();
      this.groupControl3.EndInit();
      this.groupControl3.ResumeLayout(false);
      this.groupControl3.PerformLayout();
      this.txtEczSifre3.Properties.EndInit();
      this.txtEczKullanici3.Properties.EndInit();
      this.txtEczGlnNo3.Properties.EndInit();
      this.txtEczAdi3.Properties.EndInit();
      this.txtGayriResmiSeri.Properties.EndInit();
      this.txtResmiEvrakSeri.Properties.EndInit();
      this.txtGFatDizaynNo.Properties.EndInit();
      this.txtSifre2.Properties.EndInit();
      this.txtKullaniciAdi2.Properties.EndInit();
      this.txtGlnNo2.Properties.EndInit();
      this.txtSipDizayNo.Properties.EndInit();
      this.txtFatDizaynNo.Properties.EndInit();
      this.txtNetsisSifre.Properties.EndInit();
      this.txtNetsisUser.Properties.EndInit();
      this.txtNetsisSirket.Properties.EndInit();
      this.groupControl2.EndInit();
      this.groupControl2.ResumeLayout(false);
      this.groupControl2.PerformLayout();
      this.txtEczSifre2.Properties.EndInit();
      this.txtEczKullanici2.Properties.EndInit();
      this.txtEczGlnNo2.Properties.EndInit();
      this.txtEczAdi2.Properties.EndInit();
      this.groupControl1.EndInit();
      this.groupControl1.ResumeLayout(false);
      this.groupControl1.PerformLayout();
      this.txtEczSifre1.Properties.EndInit();
      this.txtEczKullanici1.Properties.EndInit();
      this.txtEczGlnNo1.Properties.EndInit();
      this.txtEczAdi1.Properties.EndInit();
      this.chkBeseri.Properties.EndInit();
      this.txtDeaktivasyon.Properties.EndInit();
      this.txtSifre.Properties.EndInit();
      this.txtKullaniciAdi.Properties.EndInit();
      this.txtGlnNo.Properties.EndInit();
      ((ISupportInitialize) this.navigationPane1).EndInit();
      this.navigationPane1.ResumeLayout(false);
      this.ResumeLayout(false);
    }
  }
}
