-- PTS Optimizasyon: Mevcut kayıtları KALEM_SAYISI ve URUN_ADEDI ile güncelle
-- Bu script bir kere çalıştırılmalıdır

USE NETSIS
GO

-- Tüm mevcut AKTBLPTSMAS kayıtlarını AKTBLPTSTRA'dan hesaplayarak güncelle
UPDATE m SET
  KALEM_SAYISI = ISNULL(s.UNIQUE_GTIN_COUNT, 0),
  URUN_ADEDI = ISNULL(s.TOTAL_PRODUCT_COUNT, 0)
FROM AKTBLPTSMAS m
LEFT JOIN (
  SELECT 
    TRANSFER_ID,
    COUNT(DISTINCT GTIN) AS UNIQUE_GTIN_COUNT,
    COUNT(*) AS TOTAL_PRODUCT_COUNT
  FROM AKTBLPTSTRA WITH (NOLOCK)
  WHERE SERIAL_NUMBER IS NOT NULL
  GROUP BY TRANSFER_ID
) s ON s.TRANSFER_ID = m.TRANSFER_ID
WHERE m.KALEM_SAYISI IS NULL OR m.KALEM_SAYISI = 0

-- Sonucu kontrol et
SELECT 
  COUNT(*) AS TOPLAM_KAYIT,
  SUM(CASE WHEN KALEM_SAYISI > 0 THEN 1 ELSE 0 END) AS GUNCELLENEN
FROM AKTBLPTSMAS

PRINT 'Mevcut kayıtlar güncellendi!'
